apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/leketech/implementing-ci-cd-in-local-env.git'
    targetRevision: HEAD
    path: helm/app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
